### ISSUE TITLE
[Dev] Clean repo

### ISSUE THREAD

**Issue by ocots** [control-toolbox/LossControl.jl#38]
@AnasXbouali Could you remove the branch [`adjoint`](https://github.com/control-toolbox/LossControl.jl/tree/adjoint)?

Before, you can download the code if you want.

![Capture d’écran 2024-09-09 à 15 26 28](https://github.com/user-attachments/assets/17d458d1-8c9b-4f32-a4f2-4068a31a814c)

**Comment by AnasXbouali** [comment]
Done!
